### ISSUE TITLE
Consider different windows files

### ISSUE THREAD

**Issue by withinboredom** [frodeborli/serializor#1]
https://github.com/frodeborli/serializor/blob/bc3ab0e2ce49c5d2a8c05f24a8e4c4b1db270f33/Serializor.php#L54

For example:

`C:\ProgramData\Microsoft\Windows\DeviceMetadataCache\dmrc.idx` pretty much only changes when new devices are discovered (pretty rare TBH unless it is a new machine or the user buys new hardware).

`C:\Windows\System32\spp\store\2.0\{data.dat|tokens.dat}` is based on the windows activation.

**Comment by frodeborli** [comment]
Thanks for going over the code at this detail. Very helpful :-)

I changed the file names. My reasoning when picking those files was that they would have a unique timestamp regardless, so the risk of duplicate secrets between different machines would be small and in production most people will not be on Windows, and they should set the secret manually anyway.
