### ISSUE TITLE
Namespace collision in `ClosureTransformer` generated code

### ISSUE THREAD

**Issue by oruborus** [frodeborli/serializor#2]
https://github.com/frodeborli/serializor/blob/f9aecd73e5a6368a6ba32e65a78f3d8cf62eb58c/src/Transformers/ClosureTransformer.php#L180
Missing `\` before `Closure` return type hint.
This leads to namespace collision in values referencing another class called `Closure`.

**Comment by frodeborli** [comment]
I think I fixed this as well i v1.0.2, but I'm not sure how to create a test case for it.

**Comment by oruborus** [comment]
> I think I fixed this as well i v1.0.2, but I'm not sure how to create a test case for it.

I would create a fixture `\Tests\Fixtures\Closure`, serialize it and unserialize the result of that.
Without the fix the collision should occur.

I am sorry - I only got my phone on me so I can't make a pull request.
